require "open3"

class GithubReviewSubmitter
  # Base error class for all submitter errors
  class Error < StandardError; end

  # Raised when no comments are selected for submission
  class NoCommentsSelectedError < Error
    def initialize(msg = "No comments selected for submission")
      super
    end
  end

  # Raised when GitHub API rate limit is exceeded
  class RateLimitError < Error
    attr_reader :reset_at

    def initialize(reset_at = nil)
      @reset_at = reset_at
      msg = "GitHub API rate limit exceeded"
      msg += ". Try again after #{reset_at.strftime('%H:%M:%S')}" if reset_at
      super(msg)
    end
  end

  # Raised when authentication fails
  class AuthenticationError < Error
    def initialize(msg = "GitHub authentication failed. Please check your credentials.")
      super
    end
  end

  # Raised when the PR or repository is not found
  class NotFoundError < Error
    def initialize(resource = "Resource")
      super("#{resource} not found. It may have been deleted or you may not have access.")
    end
  end

  # Raised when the diff is stale (code has changed since review)
  class StaleDiffError < Error
    def initialize(file_path = nil)
      msg = "The code has changed since this review was generated"
      msg += " (#{file_path})" if file_path
      msg += ". Some comments may reference outdated line numbers."
      super(msg)
    end
  end

  # Raised when the review cannot be submitted due to branch protection or other restrictions
  class SubmissionBlockedError < Error
    def initialize(msg = "Review submission is blocked. Check branch protection rules or PR status.")
      super
    end
  end

  # GitHub review events
  EVENTS = %w[APPROVE REQUEST_CHANGES COMMENT].freeze

  def initialize(review_task:, repo_path: nil)
    @review_task = review_task
    @pull_request = review_task.pull_request
    @repo_path = repo_path || Setting.current_repo
  end

  # Submit review comments as a GitHub PR review
  # @param event [String] The review event type: APPROVE, REQUEST_CHANGES, or COMMENT
  # @param summary [String] Optional summary body for the review
  # @param comments [ActiveRecord::Relation, Array] Optional specific comments to submit (defaults to all pending)
  # @return [Hash] The response from GitHub API
  def submit_review(event: nil, summary: nil, comments: nil)
    validate_event!(event) if event.present?

    comments = comments.nil? ? @review_task.review_comments.pending : comments
    return submit_empty_review(event, summary) if comments.empty?

    review_body = build_review_body(comments, summary)
    review_event = event || determine_event(comments)
    review_comments = build_review_comments(comments)

    submit_to_github(review_body, review_event, review_comments)
  end

  # Submit a single comment to a specific file/line in the PR
  # @param comment [ReviewComment] The comment to submit
  # @return [Hash] The response from GitHub API
  def submit_single_comment(comment)
    payload = build_single_comment_payload(comment)

    run_gh_api(
      "POST",
      "/repos/#{@pull_request.repo_full_name}/pulls/#{@pull_request.number}/comments",
      payload
    )
  end

  # Submit a general PR comment (not attached to code)
  # @param body [String] The comment body
  # @return [Hash] The response from GitHub API
  def submit_general_comment(body)
    payload = { body: body }

    run_gh_api(
      "POST",
      "/repos/#{@pull_request.repo_full_name}/issues/#{@pull_request.number}/comments",
      payload
    )
  end

  private

  def validate_event!(event)
    unless EVENTS.include?(event)
      raise Error, "Invalid review event: #{event}. Must be one of: #{EVENTS.join(', ')}"
    end
  end

  def submit_empty_review(event, summary)
    review_event = event || "COMMENT"
    review_body = if review_event == "APPROVE" && summary.blank?
      nil
    else
      summary || "Review completed with no actionable comments."
    end

    submit_to_github(review_body, review_event, [])
  end

  def build_review_body(comments, custom_summary = nil)
    return custom_summary if custom_summary.present?

    counts = count_by_severity(comments)
    parts = []

    parts << "## Code Review Summary\n"
    parts << "Found **#{comments.size}** issues:\n"

    counts.each do |severity, count|
      emoji = severity_emoji(severity)
      parts << "- #{emoji} **#{severity.capitalize}**: #{count}"
    end

    parts << "\n---\n"
    parts << "_Review generated by Forge_"

    parts.join("\n")
  end

  def count_by_severity(comments)
    comments.group_by(&:severity).transform_values(&:count)
  end

  def severity_emoji(severity)
    case severity
    when "critical" then ":rotating_light:"
    when "major" then ":warning:"
    when "minor" then ":information_source:"
    when "suggestion" then ":bulb:"
    when "nitpick" then ":mag:"
    else ":speech_balloon:"
    end
  end

  def determine_event(comments)
    # Request changes if there are critical or major issues
    if comments.any? { |c| c.critical? || c.major? }
      "REQUEST_CHANGES"
    else
      "COMMENT"
    end
  end

  def build_review_comments(comments)
    comments.filter_map do |comment|
      next unless comment.file_path.present?
      next if comment.file_path.strip.casecmp("N/A").zero?

      build_comment_payload(comment)
    end
  end

  def build_comment_payload(comment)
    payload = {
      path: comment.file_path,
      body: format_comment_body(comment)
    }

    # GitHub requires either 'line' for single line or 'start_line' + 'line' for multi-line
    if comment.line_number.present?
      payload[:line] = comment.line_number
      payload[:side] = "RIGHT" # Comment on the new version of the file
    end

    payload
  end

  def build_single_comment_payload(comment)
    payload = {
      body: format_comment_body(comment),
      commit_id: fetch_latest_commit_sha,
      path: comment.file_path
    }

    if comment.line_number.present?
      payload[:line] = comment.line_number
      payload[:side] = "RIGHT"
    end

    payload
  end

  def format_comment_body(comment)
    severity_badge = severity_badge(comment.severity)
    "#{severity_badge}\n\n#{comment.body}"
  end

  def severity_badge(severity)
    case severity
    when "critical"
      "**:rotating_light: Critical**"
    when "major"
      "**:warning: Major**"
    when "minor"
      "**:information_source: Minor**"
    when "suggestion"
      "**:bulb: Suggestion**"
    when "nitpick"
      "**:mag: Nitpick**"
    else
      "**Comment**"
    end
  end

  def submit_to_github(body, event, comments)
    payload = {
      event: event
    }

    payload[:body] = body if body.present?

    # Only include comments if there are any with valid file paths
    payload[:comments] = comments if comments.any?

    response = run_gh_api(
      "POST",
      "/repos/#{@pull_request.repo_full_name}/pulls/#{@pull_request.number}/reviews",
      payload
    )

    Rails.logger.info(
      "GithubReviewSubmitter: Submitted review to PR ##{@pull_request.number} " \
      "with event=#{event}, comments=#{comments.size}"
    )

    response
  end

  def fetch_latest_commit_sha
    json = run_gh_command(
      "pr", "view", @pull_request.number.to_s,
      "--repo", @pull_request.repo_full_name,
      "--json", "headRefOid"
    )
    data = JSON.parse(json)
    data["headRefOid"]
  end

  def run_gh_api(method, endpoint, payload)
    json_payload = JSON.generate(payload)

    args = [
      "api",
      "--method", method,
      "-H", "Accept: application/vnd.github+json",
      "-H", "X-GitHub-Api-Version: 2022-11-28",
      endpoint,
      "--input", "-"
    ]

    stdout, stderr, status = run_gh_command_with_stdin(args, json_payload)

    unless status.success?
      Rails.logger.error("GithubReviewSubmitter: API error - #{stderr}")
      raise parse_api_error(stderr, stdout)
    end

    stdout.strip.empty? ? {} : JSON.parse(stdout)
  rescue JSON::ParserError => e
    Rails.logger.error("GithubReviewSubmitter: Failed to parse response - #{e.message}")
    raise Error, "Failed to parse GitHub API response: #{e.message}"
  end

  # Parse API error response and return appropriate error class
  def parse_api_error(stderr, stdout = nil)
    error_body = parse_error_body(stderr, stdout)
    error_message = error_body["message"] || stderr

    # Check for rate limiting
    if stderr.include?("rate limit") || error_message.downcase.include?("rate limit")
      reset_time = extract_rate_limit_reset(stderr)
      return RateLimitError.new(reset_time)
    end

    # Check for authentication errors
    if stderr.include?("401") || error_message.include?("Bad credentials") ||
       error_message.include?("authentication") || stderr.include?("gh auth login")
      return AuthenticationError.new
    end

    # Check for not found errors
    if stderr.include?("404") || error_message.include?("Not Found")
      return NotFoundError.new("Pull request or repository")
    end

    # Check for stale diff / invalid position errors
    if error_message.include?("position") || error_message.include?("diff") ||
       error_message.include?("line") && error_message.include?("does not exist")
      file_path = extract_file_from_error(error_body)
      return StaleDiffError.new(file_path)
    end

    # Check for submission blocked (permissions, branch protection, etc.)
    if stderr.include?("403") || error_message.include?("permission") ||
       error_message.include?("protected branch") || error_message.include?("blocked")
      return SubmissionBlockedError.new(error_message)
    end

    # Default to generic error with user-friendly message
    Error.new(format_user_friendly_error(error_message))
  end

  # Try to parse error body from stderr or stdout
  def parse_error_body(stderr, stdout)
    # Try to extract JSON from stderr first (gh cli sometimes includes it)
    if stderr.include?("{")
      json_start = stderr.index("{")
      json_str = stderr[json_start..]
      return JSON.parse(json_str) rescue {}
    end

    # Try stdout as fallback
    if stdout.present? && stdout.include?("{")
      return JSON.parse(stdout) rescue {}
    end

    {}
  end

  # Extract rate limit reset time from error message
  def extract_rate_limit_reset(stderr)
    # GitHub includes reset time in headers, but gh CLI might expose it differently
    # Try to parse common formats
    if stderr =~ /reset(?:s)?\s+(?:at\s+)?(\d{4}-\d{2}-\d{2}[T\s]\d{2}:\d{2}:\d{2})/i
      Time.parse($1) rescue nil
    elsif stderr =~ /(\d+)\s*(?:seconds?|secs?)\s*(?:remaining|until)/i
      Time.now + $1.to_i
    else
      nil
    end
  end

  # Extract file path from error body if available
  def extract_file_from_error(error_body)
    errors = error_body["errors"] || []
    errors.each do |err|
      return err["field"] if err["field"]&.include?("/")
    end
    nil
  end

  # Format error message to be more user-friendly
  def format_user_friendly_error(message)
    # Remove technical details and make message more readable
    message = message.gsub(/\s+/, " ").strip

    # Truncate very long messages
    if message.length > 200
      message = message[0, 197] + "..."
    end

    "GitHub API error: #{message}"
  end

  def run_gh_command(*args)
    options = {}
    options[:chdir] = @repo_path if @repo_path.present? && Dir.exist?(@repo_path)

    stdout, stderr, status = Open3.capture3("gh", *args, **options)
    raise Error, "GitHub CLI error: #{stderr}" unless status.success?
    stdout
  end

  def run_gh_command_with_stdin(args, stdin_data)
    options = {}
    options[:chdir] = @repo_path if @repo_path.present? && Dir.exist?(@repo_path)

    Open3.capture3("gh", *args, **options, stdin_data: stdin_data)
  end
end
