import { beforeEach, describe, expect, test } from 'bun:test'
import { RecordNotFoundError } from '../../src/lib/errors'
import type { ReviewCommentRecord } from '../../src/models/review-comment'
import type { ReviewTaskRecord } from '../../src/models/review-task'
import { SettingStore } from '../../src/models/setting'
import {
  AuthenticationError,
  buildCommentPayload,
  buildReviewBody,
  buildReviewComments,
  buildSingleCommentPayload,
  determineEvent,
  extractFileFromError,
  extractRateLimitReset,
  formatUserFriendlyError,
  GithubReviewSubmitterError,
  NotFoundError,
  parseApiError,
  RateLimitError,
  runGithubApi,
  severityBadge,
  severityEmoji,
  StaleDiffError,
  submitGeneralComment,
  submitReview,
  submitSingleComment,
  SubmissionBlockedError,
  validateEvent,
} from '../../src/services/github-review-submitter'
import { createTestContext, type TestContext } from '../support/context'
import { insertPullRequest, insertReviewComment, insertReviewTask } from '../support/factories'
import { createTempFolder } from '../support/git'

const repoOwner = 'test'
const repoName = 'repo'
const prNumber = 42
const reviewsEndpoint = `/repos/${repoOwner}/${repoName}/pulls/${prNumber}/reviews`
const emptyReviewBody = 'Review completed with no actionable comments.'

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

let ctx: TestContext
let task: ReviewTaskRecord
let criticalComment: ReviewCommentRecord
let minorComment: ReviewCommentRecord
let fileLevelComment: ReviewCommentRecord

beforeEach(() => {
  ctx = createTestContext()
  const pullRequest = insertPullRequest(ctx.db, { number: prNumber, repoOwner, repoName, reviewStatus: 'pending_review' })
  task = insertReviewTask(ctx.db, { pullRequestId: pullRequest.id, state: 'reviewed' })
  criticalComment = insertReviewComment(ctx.db, {
    reviewTaskId: task.id,
    body: 'Critical issue',
    filePath: 'app/models/user.rb',
    lineNumber: 10,
    severity: 'critical',
    status: 'pending',
  })
  minorComment = insertReviewComment(ctx.db, {
    reviewTaskId: task.id,
    body: 'Minor suggestion',
    filePath: 'app/controllers/users_controller.rb',
    lineNumber: 25,
    severity: 'minor',
    status: 'pending',
  })
  fileLevelComment = insertReviewComment(ctx.db, {
    reviewTaskId: task.id,
    body: 'General comment',
    filePath: 'README.md',
    lineNumber: null,
    severity: 'suggestion',
    status: 'pending',
  })
})

function stubGhApi(response: { stdout?: string; stderr?: string; success?: boolean } = { stdout: '{}' }) {
  ctx.commands.on(['gh', 'api'], response)
}

function lastApiCall() {
  const call = ctx.commands.commandsMatching(['gh', 'api']).at(-1)
  if (!call) throw new Error('gh api was not called')
  return call
}

function sentPayload() {
  const parsed: unknown = JSON.parse(lastApiCall().options.input ?? 'null')
  if (!isRecord(parsed)) throw new Error('gh api payload is not an object')
  return parsed
}

function sentEndpoint() {
  const { command } = lastApiCall()
  return command[command.indexOf('--input') - 1]
}

function sentMethod() {
  const { command } = lastApiCall()
  return command[command.indexOf('--method') + 1]
}

function sentComments() {
  const comments = sentPayload().comments
  if (!Array.isArray(comments)) throw new Error('payload has no comments')
  return comments
}

describe('validateEvent', () => {
  test.each(['APPROVE', 'REQUEST_CHANGES', 'COMMENT'])('accepts %s', (event) => {
    expect(() => validateEvent(event)).not.toThrow()
  })

  test('raises for an invalid event, listing the valid ones', () => {
    const invalidEvent = 'INVALID'
    const validEvents = ['APPROVE', 'REQUEST_CHANGES', 'COMMENT']

    expect(() => validateEvent(invalidEvent)).toThrow(GithubReviewSubmitterError)
    expect(() => validateEvent(invalidEvent)).toThrow(`Invalid review event: ${invalidEvent}. Must be one of: ${validEvents.join(', ')}`)
  })

  test.each(['approve', 'Approve'])('is case sensitive (%s)', (event) => {
    expect(() => validateEvent(event)).toThrow(GithubReviewSubmitterError)
  })
})

describe('buildReviewBody', () => {
  test('summarizes counts per severity', () => {
    const comments = [criticalComment, minorComment]

    const body = buildReviewBody(comments)

    expect(body).toContain('## Code Review Summary')
    expect(body).toContain(`Found **${comments.length}** issues`)
    expect(body).toContain(`- ${severityEmoji(criticalComment.severity)} **Critical**: 1`)
    expect(body).toContain(`- ${severityEmoji(minorComment.severity)} **Minor**: 1`)
  })

  test('includes the footer', () => {
    expect(buildReviewBody([criticalComment])).toContain('_Review generated by Forge_')
  })

  test('uses the custom summary when provided', () => {
    const customSummary = 'Custom summary'

    expect(buildReviewBody([criticalComment], customSummary)).toBe(customSummary)
  })
})

describe('determineEvent', () => {
  test('requests changes for critical issues', () => {
    expect(determineEvent([criticalComment])).toBe('REQUEST_CHANGES')
  })

  test('requests changes for major issues', () => {
    const majorComment = { ...criticalComment, severity: 'major' }

    expect(determineEvent([majorComment])).toBe('REQUEST_CHANGES')
  })

  test('comments for minor issues', () => {
    expect(determineEvent([minorComment])).toBe('COMMENT')
  })

  test('comments for suggestions', () => {
    expect(determineEvent([fileLevelComment])).toBe('COMMENT')
  })

  test('comments when nothing is critical or major', () => {
    expect(determineEvent([minorComment, fileLevelComment])).toBe('COMMENT')
  })

  test('requests changes with mixed severities', () => {
    expect(determineEvent([criticalComment, minorComment, fileLevelComment])).toBe('REQUEST_CHANGES')
  })
})

describe('buildReviewComments', () => {
  test('includes every comment with a file path, in order', () => {
    const comments = [criticalComment, minorComment, fileLevelComment]

    const payloads = buildReviewComments(comments)

    expect(payloads.map((payload) => payload.path)).toEqual(comments.map((comment) => comment.filePath))
  })

  test('includes line and side when the comment has a line number', () => {
    const [payload] = buildReviewComments([criticalComment])

    expect(payload?.line).toBe(criticalComment.lineNumber ?? undefined)
    expect(payload?.side).toBe('RIGHT')
  })

  test.each(['N/A', ' n/a '])('skips comments whose file path is %p', (filePath) => {
    const unmappedComment = insertReviewComment(ctx.db, { reviewTaskId: task.id, body: 'Cannot map file path', filePath, severity: 'major' })

    expect(buildReviewComments([unmappedComment])).toEqual([])
  })
})

describe('buildCommentPayload', () => {
  test('includes path, line, side and a badged body', () => {
    const payload = buildCommentPayload(criticalComment)

    expect(payload).toEqual({
      path: criticalComment.filePath,
      body: `${severityBadge(criticalComment.severity)}\n\n${criticalComment.body}`,
      line: criticalComment.lineNumber ?? undefined,
      side: 'RIGHT',
    })
  })

  test('omits line and side without a line number', () => {
    const payload = buildCommentPayload(fileLevelComment)

    expect(payload).not.toHaveProperty('line')
    expect(payload).not.toHaveProperty('side')
  })
})

describe('formatUserFriendlyError', () => {
  const prefix = 'GitHub API error: '

  test('collapses and trims whitespace', () => {
    const words = ['too', 'many', 'spaces']

    expect(formatUserFriendlyError(`  ${words.join('   ')}  `)).toBe(`${prefix}${words.join(' ')}`)
  })

  test('truncates long messages to 200 characters', () => {
    const truncatedLength = 200
    const longMessage = 'x'.repeat(300)

    const message = formatUserFriendlyError(longMessage)

    expect(message).toHaveLength(prefix.length + truncatedLength)
    expect(message.endsWith('...')).toBe(true)
  })

  test('prefixes the message', () => {
    const original = 'something went wrong'

    expect(formatUserFriendlyError(original)).toBe(`${prefix}${original}`)
  })
})

describe('severity decorations', () => {
  const emojis: Array<[string, string]> = [
    ['critical', ':rotating_light:'],
    ['major', ':warning:'],
    ['minor', ':information_source:'],
    ['suggestion', ':bulb:'],
    ['nitpick', ':mag:'],
    ['unknown', ':speech_balloon:'],
  ]
  test.each(emojis)('severityEmoji(%p) is %p', (severity, emoji) => {
    expect(severityEmoji(severity)).toBe(emoji)
  })

  const badges: Array<[string, string]> = [
    ['critical', '**:rotating_light: Critical**'],
    ['major', '**:warning: Major**'],
    ['minor', '**:information_source: Minor**'],
    ['suggestion', '**:bulb: Suggestion**'],
    ['nitpick', '**:mag: Nitpick**'],
    ['unknown', '**Comment**'],
  ]
  test.each(badges)('severityBadge(%p) is %p', (severity, badge) => {
    expect(severityBadge(severity)).toBe(badge)
  })
})

describe('extractRateLimitReset', () => {
  test('parses an ISO8601 timestamp as local time, ignoring the zone suffix like Ruby', () => {
    const [year, month, day, hour] = [2024, 1, 1, 12]
    const stderr = `rate limit resets at ${year}-0${month}-0${day}T${hour}:00:00Z`

    expect(extractRateLimitReset(stderr)).toEqual(new Date(year, month - 1, day, hour, 0, 0))
  })

  test('parses a seconds countdown relative to now', () => {
    const now = new Date()
    const seconds = 300

    expect(extractRateLimitReset(`rate limit resets in ${seconds} seconds remaining`, now)).toEqual(new Date(now.getTime() + seconds * 1000))
  })

  test('returns null for unknown formats', () => {
    expect(extractRateLimitReset('unknown error format')).toBeNull()
  })
})

describe('extractFileFromError', () => {
  test('returns the first field that looks like a path', () => {
    const filePath = 'app/models/user.rb'

    expect(extractFileFromError({ errors: [{ field: filePath, message: 'Invalid position' }] })).toBe(filePath)
  })

  test('returns null for non-file fields', () => {
    expect(extractFileFromError({ errors: [{ field: 'body', message: 'Invalid body' }] })).toBeNull()
  })

  test('returns null without errors', () => {
    expect(extractFileFromError({ message: 'error' })).toBeNull()
  })
})

describe('parseApiError', () => {
  test('returns RateLimitError with the reset time', () => {
    const [year, month, day, hour] = [2024, 1, 1, 12]
    const resetAt = new Date(year, month - 1, day, hour, 0, 0)

    const error = parseApiError(`API rate limit exceeded; resets at ${year}-0${month}-0${day}T${hour}:00:00`)

    expect(error).toBeInstanceOf(RateLimitError)
    expect(error instanceof RateLimitError ? error.resetAt : null).toEqual(resetAt)
    expect(error.message).toBe(`GitHub API rate limit exceeded. Try again after ${hour}:00:00`)
  })

  test('returns RateLimitError without a reset time', () => {
    const error = parseApiError('API rate limit exceeded')

    expect(error.message).toBe('GitHub API rate limit exceeded')
  })

  test.each(['HTTP 401 Unauthorized', 'Bad credentials', 'To get started with GitHub CLI, please run:  gh auth login'])(
    'returns AuthenticationError for %p',
    (stderr) => {
      expect(parseApiError(stderr)).toBeInstanceOf(AuthenticationError)
    },
  )

  test('returns NotFoundError for 404 errors', () => {
    const error = parseApiError('HTTP 404 Not Found')

    expect(error).toBeInstanceOf(NotFoundError)
    expect(error.message).toBe('Pull request or repository not found. It may have been deleted or you may not have access.')
  })

  test('returns StaleDiffError naming the file for position errors in stdout', () => {
    const filePath = 'app/models/user.rb'
    const stdout = JSON.stringify({ message: 'position is invalid', errors: [{ field: filePath, message: 'position invalid' }] })

    const error = parseApiError('Validation failed', stdout)

    expect(error).toBeInstanceOf(StaleDiffError)
    expect(error.message).toContain(filePath)
  })

  test('returns StaleDiffError for diff errors', () => {
    expect(parseApiError('diff hunk is outdated')).toBeInstanceOf(StaleDiffError)
  })

  test('returns SubmissionBlockedError for 403 errors', () => {
    const stderr = 'HTTP 403 Forbidden'

    const error = parseApiError(stderr)

    expect(error).toBeInstanceOf(SubmissionBlockedError)
    expect(error.message).toBe(stderr)
  })

  test('returns SubmissionBlockedError for protected branches', () => {
    expect(parseApiError('Review blocked by protected branch policy')).toBeInstanceOf(SubmissionBlockedError)
  })

  test('returns a generic error with a friendly message otherwise', () => {
    const error = parseApiError('  weird   failure   happened ')

    expect(error.constructor).toBe(GithubReviewSubmitterError)
    expect(error.message).toBe('GitHub API error: weird failure happened')
  })

  test('prefers the JSON message embedded in stderr', () => {
    const message = 'Unprocessable thing'
    const stderr = `gh: ${message} (HTTP 422)\n${JSON.stringify({ message })}`

    expect(parseApiError(stderr).message).toBe(`GitHub API error: ${message}`)
  })

  test('falls through to stdout when the JSON in stderr does not parse', () => {
    const message = 'Pull request review thread line must be part of the diff'
    const stdout = JSON.stringify({ message })

    const error = parseApiError('gh: broken {json', stdout)

    expect(error).toBeInstanceOf(StaleDiffError)
  })
})

describe('runGithubApi', () => {
  const request = { method: 'POST', endpoint: '/test', payload: { body: 'hi' } }

  test('raises on a non-JSON response', async () => {
    stubGhApi({ stdout: 'not json' })

    const run = runGithubApi(ctx, task, request)

    await expect(run).rejects.toBeInstanceOf(GithubReviewSubmitterError)
    await expect(run).rejects.toThrow('Failed to parse GitHub API response')
  })

  test('returns an empty object for an empty response', async () => {
    stubGhApi({ stdout: '  \n' })

    expect(await runGithubApi(ctx, task, request)).toEqual({})
  })

  test('parses a JSON response', async () => {
    const response = { ok: true }
    stubGhApi({ stdout: JSON.stringify(response) })

    expect(await runGithubApi(ctx, task, request)).toEqual(response)
  })

  test('sends the payload on stdin with the GitHub API headers', async () => {
    stubGhApi()

    await runGithubApi(ctx, task, request)

    expect(lastApiCall().command).toEqual([
      'gh',
      'api',
      '--method',
      request.method,
      '-H',
      'Accept: application/vnd.github+json',
      '-H',
      'X-GitHub-Api-Version: 2022-11-28',
      request.endpoint,
      '--input',
      '-',
    ])
    expect(sentPayload()).toEqual(request.payload)
  })

  test('raises the parsed API error when gh fails', async () => {
    stubGhApi({ success: false, stderr: 'HTTP 404 Not Found' })

    await expect(runGithubApi(ctx, task, request)).rejects.toBeInstanceOf(NotFoundError)
  })

  test('runs gh inside the current repo when it exists', async () => {
    const repo = createTempFolder()
    new SettingStore(ctx.db).setCurrentRepo(repo.path)
    stubGhApi()

    await runGithubApi(ctx, task, request)

    expect(lastApiCall().options.cwd).toBe(repo.path)
    repo.remove()
  })

  test('runs gh without a working directory when the current repo is missing', async () => {
    new SettingStore(ctx.db).setCurrentRepo('/tmp/forge-missing-repo-folder')
    stubGhApi()

    await runGithubApi(ctx, task, request)

    expect(lastApiCall().options.cwd).toBeUndefined()
  })
})

describe('submitReview', () => {
  test('omits the body for an approval without a summary', async () => {
    stubGhApi()

    await submitReview(ctx, task, { event: 'APPROVE', summary: null, comments: [] })

    expect(sentMethod()).toBe('POST')
    expect(sentEndpoint()).toBe(reviewsEndpoint)
    expect(sentPayload()).toEqual({ event: 'APPROVE' })
  })

  test('respects explicitly empty comments instead of falling back to pending ones', async () => {
    stubGhApi()

    await submitReview(ctx, task, { event: 'APPROVE', comments: [] })

    expect(sentPayload()).not.toHaveProperty('comments')
  })

  test('submits every pending comment by default', async () => {
    const pendingCount = 3
    stubGhApi()

    await submitReview(ctx, task)

    expect(sentEndpoint()).toBe(reviewsEndpoint)
    expect(sentPayload().event).toBe('REQUEST_CHANGES')
    expect(sentComments()).toHaveLength(pendingCount)
    expect(sentPayload().body).toContain(`Found **${pendingCount}** issues`)
  })

  test('uses an explicit event', async () => {
    const event = 'APPROVE'
    stubGhApi()

    await submitReview(ctx, task, { event })

    expect(sentPayload().event).toBe(event)
  })

  test('uses a custom summary as the body', async () => {
    const summary = 'Custom summary'
    stubGhApi()

    await submitReview(ctx, task, { summary })

    expect(sentPayload().body).toBe(summary)
  })

  test('submits an empty COMMENT review with the default body', async () => {
    stubGhApi()

    await submitReview(ctx, task, { comments: [] })

    expect(sentPayload()).toEqual({ event: 'COMMENT', body: emptyReviewBody })
  })

  test('submits only the given comments', async () => {
    stubGhApi()

    await submitReview(ctx, task, { comments: [minorComment] })

    const [comment] = sentComments()
    expect(sentPayload().event).toBe('COMMENT')
    expect(sentComments()).toHaveLength(1)
    expect(isRecord(comment) ? comment.path : null).toBe(minorComment.filePath)
  })

  test('skips N/A comments but still counts them in the summary', async () => {
    const unmapped = insertReviewComment(ctx.db, { reviewTaskId: task.id, body: 'Unmapped', filePath: 'N/A', severity: 'minor' })
    const comments = [minorComment, unmapped]
    stubGhApi()

    await submitReview(ctx, task, { comments })

    expect(sentComments()).toHaveLength(1)
    expect(sentPayload().body).toContain(`Found **${comments.length}** issues`)
  })

  test('resolves to the parsed GitHub response', async () => {
    const response = { id: 99, state: 'COMMENTED' }
    stubGhApi({ stdout: JSON.stringify(response) })

    expect(await submitReview(ctx, task, { event: 'COMMENT', summary: null, comments: [minorComment] })).toEqual(response)
  })

  test('validates the event before calling GitHub', async () => {
    stubGhApi()

    await expect(submitReview(ctx, task, { event: 'MERGE' })).rejects.toBeInstanceOf(GithubReviewSubmitterError)
    expect(ctx.commands.calls).toHaveLength(0)
  })

  test('fails when the pull request is archived, like the scoped association', async () => {
    const archived = insertPullRequest(ctx.db, { archived: true })
    const archivedTask = insertReviewTask(ctx.db, { pullRequestId: archived.id, state: 'reviewed' })
    stubGhApi()

    await expect(submitReview(ctx, archivedTask, { comments: [] })).rejects.toBeInstanceOf(RecordNotFoundError)
    expect(ctx.commands.calls).toHaveLength(0)
  })
})

describe('single and general comments', () => {
  const headSha = 'abc123'

  function stubHeadSha() {
    ctx.commands.on(['gh', 'pr', 'view'], { stdout: JSON.stringify({ headRefOid: headSha }) })
  }

  test('submitSingleComment posts to the review comments endpoint', async () => {
    stubHeadSha()
    stubGhApi()

    await submitSingleComment(ctx, task, criticalComment)

    expect(sentMethod()).toBe('POST')
    expect(sentEndpoint()).toBe(`/repos/${repoOwner}/${repoName}/pulls/${prNumber}/comments`)
    expect(sentPayload()).toMatchObject({ path: criticalComment.filePath, commit_id: headSha, line: criticalComment.lineNumber, side: 'RIGHT' })
    expect(ctx.commands.commandsMatching(['gh', 'pr', 'view'])[0]?.command).toEqual([
      'gh',
      'pr',
      'view',
      String(prNumber),
      '--repo',
      `${repoOwner}/${repoName}`,
      '--json',
      'headRefOid',
    ])
  })

  test('submitSingleComment raises a CLI error when the head commit lookup fails', async () => {
    const stderr = 'no pull requests found'
    ctx.commands.on(['gh', 'pr', 'view'], { success: false, stderr })

    await expect(submitSingleComment(ctx, task, criticalComment)).rejects.toThrow(`GitHub CLI error: ${stderr}`)
  })

  test('submitGeneralComment posts to the issue comments endpoint', async () => {
    const body = 'General note'
    stubGhApi()

    await submitGeneralComment(ctx, task, body)

    expect(sentEndpoint()).toBe(`/repos/${repoOwner}/${repoName}/issues/${prNumber}/comments`)
    expect(sentPayload()).toEqual({ body })
  })

  test('buildSingleCommentPayload includes the head commit and path', async () => {
    stubHeadSha()

    const payload = await buildSingleCommentPayload(ctx, task, criticalComment)

    expect(payload.commit_id).toBe(headSha)
    expect(payload.path).toBe(criticalComment.filePath)
  })

  test('buildSingleCommentPayload includes line and side for line comments', async () => {
    stubHeadSha()

    const payload = await buildSingleCommentPayload(ctx, task, criticalComment)

    expect(payload.line).toBe(criticalComment.lineNumber ?? undefined)
    expect(payload.side).toBe('RIGHT')
  })
})
