require "test_helper"

class GithubReviewSubmitterTest < ActiveSupport::TestCase
  setup do
    @pr = PullRequest.create!(
      github_id: 12345,
      number: 42,
      title: "Test PR",
      url: "https://github.com/test/repo/pull/42",
      repo_owner: "test",
      repo_name: "repo",
      review_status: "pending_review"
    )
    @review_task = ReviewTask.create!(
      pull_request: @pr,
      state: "reviewed"
    )

    @comment1 = ReviewComment.create!(
      review_task: @review_task,
      body: "Critical issue",
      file_path: "app/models/user.rb",
      line_number: 10,
      severity: "critical",
      status: "pending"
    )

    @comment2 = ReviewComment.create!(
      review_task: @review_task,
      body: "Minor suggestion",
      file_path: "app/controllers/users_controller.rb",
      line_number: 25,
      severity: "minor",
      status: "pending"
    )

    @comment3 = ReviewComment.create!(
      review_task: @review_task,
      body: "General comment",
      file_path: "README.md",
      line_number: nil,
      severity: "suggestion",
      status: "pending"
    )

    @submitter = GithubReviewSubmitter.new(review_task: @review_task)
  end

  teardown do
    @pr&.destroy
    @review_task&.destroy
  end

  def status(success)
    stub(success?: success)
  end

  # validate_event! tests
  test "validate_event! accepts APPROVE" do
    assert_nothing_raised do
      @submitter.send(:validate_event!, "APPROVE")
    end
  end

  test "validate_event! accepts REQUEST_CHANGES" do
    assert_nothing_raised do
      @submitter.send(:validate_event!, "REQUEST_CHANGES")
    end
  end

  test "validate_event! accepts COMMENT" do
    assert_nothing_raised do
      @submitter.send(:validate_event!, "COMMENT")
    end
  end

  test "validate_event! raises Error for invalid event" do
    error = assert_raises(GithubReviewSubmitter::Error) do
      @submitter.send(:validate_event!, "INVALID")
    end

    assert_includes error.message, "Invalid review event"
    assert_includes error.message, "INVALID"
    assert_includes error.message, "APPROVE"
    assert_includes error.message, "REQUEST_CHANGES"
    assert_includes error.message, "COMMENT"
  end

  test "validate_event! is case sensitive" do
    assert_raises(GithubReviewSubmitter::Error) do
      @submitter.send(:validate_event!, "approve")
    end

    assert_raises(GithubReviewSubmitter::Error) do
      @submitter.send(:validate_event!, "Approve")
    end
  end

  # build_review_body tests
  test "build_review_body generates correct summary" do
    body = @submitter.send(:build_review_body, [ @comment1, @comment2 ])

    assert_includes body, "## Code Review Summary"
    assert_includes body, "Found **2** issues"
    assert_includes body, ":rotating_light:"
    assert_includes body, ":information_source:"
    assert_includes body, "Critical"
    assert_includes body, "Minor"
  end

  test "build_review_body includes footer" do
    body = @submitter.send(:build_review_body, [ @comment1 ])

    assert_includes body, "_Review generated by Forge_"
  end

  test "build_review_body uses custom summary when provided" do
    body = @submitter.send(:build_review_body, [ @comment1 ], "Custom summary")

    assert_equal "Custom summary", body
  end

  # determine_event tests
  test "determine_event returns REQUEST_CHANGES for critical issues" do
    event = @submitter.send(:determine_event, [ @comment1 ])
    assert_equal "REQUEST_CHANGES", event
  end

  test "determine_event returns REQUEST_CHANGES for major issues" do
    @comment1.update!(severity: "major")
    event = @submitter.send(:determine_event, [ @comment1 ])
    assert_equal "REQUEST_CHANGES", event
  end

  test "determine_event returns COMMENT for minor issues" do
    event = @submitter.send(:determine_event, [ @comment2 ])
    assert_equal "COMMENT", event
  end

  test "determine_event returns COMMENT for suggestion" do
    event = @submitter.send(:determine_event, [ @comment3 ])
    assert_equal "COMMENT", event
  end

  test "determine_event returns COMMENT when no critical/major issues" do
    event = @submitter.send(:determine_event, [ @comment2, @comment3 ])
    assert_equal "COMMENT", event
  end

  test "determine_event returns REQUEST_CHANGES with mixed severities" do
    event = @submitter.send(:determine_event, [ @comment1, @comment2, @comment3 ])
    assert_equal "REQUEST_CHANGES", event
  end

  # build_review_comments tests
  test "build_review_comments includes comments with file_path" do
    comments = @submitter.send(:build_review_comments, [ @comment1, @comment2, @comment3 ])

    assert_equal 3, comments.length
    assert_equal "app/models/user.rb", comments[0][:path]
    assert_equal "app/controllers/users_controller.rb", comments[1][:path]
    assert_equal "README.md", comments[2][:path]
  end

  test "build_review_comments includes line_number when present" do
    comments = @submitter.send(:build_review_comments, [ @comment1 ])

    assert_equal 10, comments[0][:line]
    assert_equal "RIGHT", comments[0][:side]
  end

  test "build_review_comments skips comments with N/A file path" do
    unknown_path_comment = ReviewComment.create!(
      review_task: @review_task,
      body: "Cannot map file path",
      file_path: "N/A",
      severity: "major",
      status: "pending"
    )

    comments = @submitter.send(:build_review_comments, [ unknown_path_comment ])

    assert_equal [], comments
  end

  # build_comment_payload tests
  test "build_comment_payload includes all fields" do
    payload = @submitter.send(:build_comment_payload, @comment1)

    assert_equal "app/models/user.rb", payload[:path]
    assert_equal 10, payload[:line]
    assert_equal "RIGHT", payload[:side]
    assert_includes payload[:body], "Critical issue"
    assert_includes payload[:body], ":rotating_light:"
  end

  test "build_comment_payload omits line when line_number is nil" do
    payload = @submitter.send(:build_comment_payload, @comment3)

    assert_nil payload[:line]
    assert_nil payload[:side]
  end

  # format_user_friendly_error tests
  test "format_user_friendly_error trims whitespace" do
    error_msg = @submitter.send(:format_user_friendly_error, "  too   many   spaces  ")
    assert_equal "GitHub API error: too many spaces", error_msg
  end

  test "format_user_friendly_error truncates long messages" do
    long_msg = "x" * 300
    error_msg = @submitter.send(:format_user_friendly_error, long_msg)
    # Prefix "GitHub API error: " is 18 chars, message is truncated to 197 + "..." = 200
    # Total: 18 + 197 + 3 = 218 chars
    assert_equal 218, error_msg.length
    assert error_msg.end_with?("...")
  end

  test "format_user_friendly_error prefixes with GitHub API error" do
    error_msg = @submitter.send(:format_user_friendly_error, "something went wrong")
    assert_equal "GitHub API error: something went wrong", error_msg
  end

  # severity_emoji tests
  test "severity_emoji returns correct emoji for critical" do
    emoji = @submitter.send(:severity_emoji, "critical")
    assert_equal ":rotating_light:", emoji
  end

  test "severity_emoji returns correct emoji for major" do
    emoji = @submitter.send(:severity_emoji, "major")
    assert_equal ":warning:", emoji
  end

  test "severity_emoji returns correct emoji for minor" do
    emoji = @submitter.send(:severity_emoji, "minor")
    assert_equal ":information_source:", emoji
  end

  test "severity_emoji returns correct emoji for suggestion" do
    emoji = @submitter.send(:severity_emoji, "suggestion")
    assert_equal ":bulb:", emoji
  end

  test "severity_emoji returns correct emoji for nitpick" do
    emoji = @submitter.send(:severity_emoji, "nitpick")
    assert_equal ":mag:", emoji
  end

  test "severity_emoji returns default for unknown" do
    emoji = @submitter.send(:severity_emoji, "unknown")
    assert_equal ":speech_balloon:", emoji
  end

  # severity_badge tests
  test "severity_badge returns correct badge for critical" do
    badge = @submitter.send(:severity_badge, "critical")
    assert_equal "**:rotating_light: Critical**", badge
  end

  test "severity_badge returns correct badge for major" do
    badge = @submitter.send(:severity_badge, "major")
    assert_equal "**:warning: Major**", badge
  end

  test "severity_badge returns correct badge for minor" do
    badge = @submitter.send(:severity_badge, "minor")
    assert_equal "**:information_source: Minor**", badge
  end

  test "severity_badge returns correct badge for suggestion" do
    badge = @submitter.send(:severity_badge, "suggestion")
    assert_equal "**:bulb: Suggestion**", badge
  end

  test "severity_badge returns correct badge for nitpick" do
    badge = @submitter.send(:severity_badge, "nitpick")
    assert_equal "**:mag: Nitpick**", badge
  end

  test "severity_badge returns default for unknown" do
    badge = @submitter.send(:severity_badge, "unknown")
    assert_equal "**Comment**", badge
  end

  # extract_rate_limit_reset tests
  test "extract_rate_limit_reset parses ISO8601 format" do
    stderr = "rate limit resets at 2024-01-01T12:00:00Z"
    reset_time = @submitter.send(:extract_rate_limit_reset, stderr)
    # Time.parse converts to local timezone, so use large delta
    expected = Time.parse("2024-01-01T12:00:00Z")
    assert_in_delta expected, reset_time, 10800 # 3 hour tolerance for timezone
  end

  test "extract_rate_limit_reset parses seconds format" do
    stderr = "rate limit resets in 300 seconds remaining"
    reset_time = @submitter.send(:extract_rate_limit_reset, stderr)
    assert_in_delta Time.now + 300, reset_time, 1
  end

  test "extract_rate_limit_reset returns nil for unknown format" do
    stderr = "unknown error format"
    reset_time = @submitter.send(:extract_rate_limit_reset, stderr)
    assert_nil reset_time
  end

  # extract_file_from_error tests
  test "extract_file_from_error extracts file from error body" do
    error_body = {
      "errors" => [
        { "field" => "app/models/user.rb", "message" => "Invalid position" }
      ]
    }
    file = @submitter.send(:extract_file_from_error, error_body)
    assert_equal "app/models/user.rb", file
  end

  test "extract_file_from_error returns nil for non-file fields" do
    error_body = {
      "errors" => [
        { "field" => "body", "message" => "Invalid body" }
      ]
    }
    file = @submitter.send(:extract_file_from_error, error_body)
    assert_nil file
  end

  test "extract_file_from_error returns nil when no errors" do
    error_body = { "message" => "error" }
    file = @submitter.send(:extract_file_from_error, error_body)
    assert_nil file
  end

  test "submit_empty_review omits review body for approve without summary" do
    @submitter.expects(:run_gh_api).with do |http_method, path, payload|
      assert_equal "POST", http_method
      assert_equal "/repos/test/repo/pulls/42/reviews", path
      assert_equal "APPROVE", payload[:event]
      assert_not payload.key?(:body)
      assert_not payload.key?(:comments)
      true
    end.returns({})

    @submitter.send(:submit_empty_review, "APPROVE", nil)
  end

  test "submit_review respects explicitly empty comments without falling back to pending" do
    @submitter.expects(:run_gh_api).with do |http_method, path, payload|
      assert_equal "POST", http_method
      assert_equal "/repos/test/repo/pulls/42/reviews", path
      assert_equal "APPROVE", payload[:event]
      assert_not payload.key?(:comments)
      true
    end.returns({})

    @submitter.submit_review(event: "APPROVE", comments: @review_task.review_comments.none)
  end

  test "submit_review with pending comments" do
    @submitter.expects(:run_gh_api).with do |http_method, path, payload|
      assert_equal "POST", http_method
      assert_equal "/repos/test/repo/pulls/42/reviews", path
      assert_equal "REQUEST_CHANGES", payload[:event]
      assert_equal 3, payload[:comments].length
      assert_includes payload[:body], "Found **3** issues"
      true
    end.returns({})

    @submitter.submit_review
  end

  test "submit_review with custom event" do
    @submitter.expects(:run_gh_api).with do |_http_method, _path, payload|
      assert_equal "APPROVE", payload[:event]
      true
    end.returns({})

    @submitter.submit_review(event: "APPROVE")
  end

  test "submit_review with custom summary" do
    @submitter.expects(:run_gh_api).with do |_http_method, _path, payload|
      assert_equal "Custom summary", payload[:body]
      true
    end.returns({})

    @submitter.submit_review(summary: "Custom summary")
  end

  test "submit_review with empty comments" do
    @submitter.expects(:run_gh_api).with do |_http_method, _path, payload|
      assert_equal "COMMENT", payload[:event]
      assert_equal "Review completed with no actionable comments.", payload[:body]
      assert_not payload.key?(:comments)
      true
    end.returns({})

    @submitter.submit_review(comments: [])
  end

  test "submit_review with specific comments" do
    @submitter.expects(:run_gh_api).with do |_http_method, _path, payload|
      assert_equal "COMMENT", payload[:event]
      assert_equal 1, payload[:comments].length
      assert_equal "app/controllers/users_controller.rb", payload[:comments][0][:path]
      true
    end.returns({})

    @submitter.submit_review(comments: [ @comment2 ])
  end

  test "parse_api_error returns RateLimitError for rate limit errors" do
    error = @submitter.send(:parse_api_error, "API rate limit exceeded; resets at 2024-01-01T12:00:00")
    assert_instance_of GithubReviewSubmitter::RateLimitError, error
    assert_equal Time.parse("2024-01-01T12:00:00"), error.reset_at
  end

  test "parse_api_error returns AuthenticationError for 401 errors" do
    error = @submitter.send(:parse_api_error, "HTTP 401 Unauthorized")
    assert_instance_of GithubReviewSubmitter::AuthenticationError, error
  end

  test "parse_api_error returns AuthenticationError for bad credentials" do
    error = @submitter.send(:parse_api_error, "Bad credentials")
    assert_instance_of GithubReviewSubmitter::AuthenticationError, error
  end

  test "parse_api_error returns NotFoundError for 404 errors" do
    error = @submitter.send(:parse_api_error, "HTTP 404 Not Found")
    assert_instance_of GithubReviewSubmitter::NotFoundError, error
  end

  test "parse_api_error returns StaleDiffError for position errors" do
    stdout = {
      message: "position is invalid",
      errors: [
        { field: "app/models/user.rb", message: "position invalid" }
      ]
    }.to_json

    error = @submitter.send(:parse_api_error, "Validation failed", stdout)
    assert_instance_of GithubReviewSubmitter::StaleDiffError, error
    assert_includes error.message, "app/models/user.rb"
  end

  test "parse_api_error returns StaleDiffError for diff errors" do
    error = @submitter.send(:parse_api_error, "diff hunk is outdated")
    assert_instance_of GithubReviewSubmitter::StaleDiffError, error
  end

  test "parse_api_error returns SubmissionBlockedError for 403 errors" do
    error = @submitter.send(:parse_api_error, "HTTP 403 Forbidden")
    assert_instance_of GithubReviewSubmitter::SubmissionBlockedError, error
  end

  test "parse_api_error returns SubmissionBlockedError for protected branch" do
    error = @submitter.send(:parse_api_error, "Review blocked by protected branch policy")
    assert_instance_of GithubReviewSubmitter::SubmissionBlockedError, error
  end

  test "parse_api_error returns generic Error for unknown errors" do
    error = @submitter.send(:parse_api_error, "  weird   failure   happened ")
    assert_instance_of GithubReviewSubmitter::Error, error
    assert_equal "GitHub API error: weird failure happened", error.message
  end

  test "run_gh_api handles non-JSON responses" do
    @submitter.expects(:run_gh_command_with_stdin).returns(["not json", "", status(true)])

    error = assert_raises(GithubReviewSubmitter::Error) do
      @submitter.send(:run_gh_api, "POST", "/test", { body: "hi" })
    end

    assert_includes error.message, "Failed to parse GitHub API response"
  end

  test "run_gh_api returns empty hash for empty response" do
    @submitter.expects(:run_gh_command_with_stdin).returns(["  \n", "", status(true)])

    assert_equal({}, @submitter.send(:run_gh_api, "POST", "/test", { body: "hi" }))
  end

  test "run_gh_api parses JSON response" do
    @submitter.expects(:run_gh_command_with_stdin).returns([{ ok: true }.to_json, "", status(true)])

    assert_equal({ "ok" => true }, @submitter.send(:run_gh_api, "POST", "/test", { body: "hi" }))
  end

  test "submit_single_comment submits single comment" do
    @submitter.stubs(:fetch_latest_commit_sha).returns("abc123")
    @submitter.expects(:run_gh_api).with(
      "POST",
      "/repos/test/repo/pulls/42/comments",
      has_entries(path: "app/models/user.rb", commit_id: "abc123", line: 10, side: "RIGHT")
    ).returns({})

    @submitter.submit_single_comment(@comment1)
  end

  test "submit_general_comment submits general comment" do
    @submitter.expects(:run_gh_api).with(
      "POST",
      "/repos/test/repo/issues/42/comments",
      { body: "General note" }
    ).returns({})

    @submitter.submit_general_comment("General note")
  end

  test "build_single_comment_payload includes commit_id" do
    @submitter.stubs(:fetch_latest_commit_sha).returns("abc123")

    payload = @submitter.send(:build_single_comment_payload, @comment1)

    assert_equal "abc123", payload[:commit_id]
    assert_equal "app/models/user.rb", payload[:path]
  end

  test "build_single_comment_payload includes line and side for comments with line_number" do
    @submitter.stubs(:fetch_latest_commit_sha).returns("abc123")

    payload = @submitter.send(:build_single_comment_payload, @comment1)

    assert_equal 10, payload[:line]
    assert_equal "RIGHT", payload[:side]
  end
end
